services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    environment:
      - PORT=3000
      - API_BASE_URL=http://dev-api.xxx.jp

  backend:
    build: ./backend
    environment:
      - PORT=3001

networks:
  default:
    name: app_network
