services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

networks:
  default:
    name: app_network
